spring:
  application:
    name: adg-rule
  profiles:
    active: prod  #切换至 dev 即可输出调试信息

logging:
  file:
    path: ./logs


application:
  config:
    expected_quantity: 2000000  #预期规则数量
    fault_tolerance: 0.001 #容错率
    warn_limit: 7 #警告阈值, 规则长度小于该值时会输出警告日志
    batch_size: 10000 #写入文件的批次大小

  # 规则源配置，remote为远程规则，local为本地规则，支持多个规则源
  rule:

    # 仅支持 http/https，不限定响应内容格式
    remote:
      - name: ADgk
        path: https://raw.githubusercontent.com/banbendalao/ADgk/master/ADgk.txt
    
      - name: AdGuard Base filter
        path: https://raw.githubusercontent.com/AdguardTeam/FiltersRegistry/master/filters/filter_2_Base/filter.txt
        
      - name: AdGuard Chinese
        path: https://raw.githubusercontent.com/AdguardTeam/FiltersRegistry/master/filters/filter_224_Chinese/filter.txt
        
      - name: AdGuard Annoyances filter
        path: https://raw.githubusercontent.com/AdguardTeam/FiltersRegistry/master/filters/filter_14_Annoyances/filter.txt
        
      - name: EasyList
        path: https://easylist-downloads.adblockplus.org/easylist.txt
        
      - name: EasyList China
        path: https://easylist-downloads.adblockplus.org/easylistchina.txt
        
      - name: EasyPrivacy
        path: https://easylist-downloads.adblockplus.org/easyprivacy.txt
        
      - name: Fanboy's Annoyance List
        path: https://easylist.to/easylist/fanboy-social.txt
        
      - name: EasyList Cookie List
        path: https://secure.fanboy.co.nz/fanboy-cookiemonster.txt
        
      - name: CJX's Annoyance List
        path: https://raw.githubusercontent.com/cjx82630/cjxlist/master/cjx-annoyance.txt
        
      - name: 乘风视频规则
        path: https://raw.githubusercontent.com/xinggsf/Adblock-Plus-Rule/master/mv.txt
        
      - name: 乘风 广告过滤规则
        path: https://raw.githubusercontent.com/xinggsf/Adblock-Plus-Rule/master/rule.txt
        
      - name: 乘风 小众视频规则
        path: https://raw.githubusercontent.com/xinggsf/Adblock-Plus-Rule/master/minority-mv.txt
         
      - name: NoAppDownload
        path: https://raw.githubusercontent.com/Noyllopa/NoAppDownload/master/NoAppDownload.txt
    
      - name: I don't care about cookies
        path: https://www.i-dont-care-about-cookies.eu/abp/

      - name: Adblock Warning Removal List
        path: https://easylist-downloads.adblockplus.org/antiadblockfilters.txt
        
      - name: damengzhu
        path: https://raw.githubusercontent.com/damengzhu/banad/main/jiekouAD.txt
        
    #本地规则
    local: #本地规则请将文件移动到项目路径rule目录中
      - name: 'private List'
        path: 'private.txt'

  output:
    file_header: |  #输出文件头, 占位符${name}将被替换为文件名，如all.txt,  ${date} 将被替换为当前日期
      [Adblock Plus 2.0]
      ! Title:AdBlock Rules Add
      ! Homepage: https://github.com/Sereinfy/Adrules
      ! Last Modified: ${date}

    path: rule   #规则文件输出路径，相对路径默认从 项目目录开始
    files:
      filters.txt:  #输出文件名
        - MODIFY  #修饰规则，添加了一些修饰符号的规则，AdG支持
      dns.txt:
        - DOMAIN  #域名规则，仅完整域名
        - REGEX   #正则规则，包含正则的域名规则，AdGH支持
        - HOSTS   #Hosts规则
