name: Generate Blacklist
on: 
  schedule:
  - cron: 0 14 * * *
  workflow_dispatch:
env:
  TZ: Asia/Shanghai

jobs:
  Generate_Blacklist:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@main

      - name: Setup Python 3.9.x
        uses: actions/setup-python@main
        with:
          python-version: '3.9.x'

      - name: Install Dependencies
        run: |
          sudo timedatectl set-timezone "$TZ"
          python -m pip install --upgrade pip
          pip install -U requests tld tcping IPy dnspython

      - name: Generate Blacklist
        run: |
          python blacklist.py
          rm -rf __pycache__

      - name: Commit Changes
        id: commit
        run: |
          if [ -z "$(git status --porcelain)" ]; then 
              exit 0
          else
            echo "status=success" >> $GITHUB_OUTPUT
            git add .
            git config --local user.email "action@github.com"
            git config --local user.name "GitHub Action"
            git commit -m "Updated at $(date)" -a
            git push -f -u origin main
          fi
            
      - name: GitHub Push
        if: steps.commit.outputs.status == 'success' && !cancelled()
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.ref }}
          
      - name: Delete workflow runs 
        uses: Mattraks/delete-workflow-runs@main
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          repository: ${{ github.repository }}
          retain_days: 0
          keep_minimum_runs: 1
