name: Merge Rules

on: 
  workflow_dispatch:
  schedule:
    - cron: 0 17 * * *
    
jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
          
      - name: Update Rules
        continue-on-error: true
        run: |
          bash ./data/script/update-rules.sh      
        
      - name: Update ReadMe
        run: |
          bash ./data/script/clean-readme.sh
          
      - name: Git push assets to Github
        run: |
          git init
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git branch -m main
          git add --all
          git commit -m "Updated at $(date)" -a
          git push -f -u origin main

      - name: Delete workflow runs 
        uses: Mattraks/delete-workflow-runs@main
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          repository: ${{ github.repository }}
          retain_days: 0
          keep_minimum_runs: 1
